apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: gitaction
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
      - name: runner
        image: tgtanya/runner:latest
        env:
        - name: GITHUB_OWNER
          value: tgtanya
        - name: GITHUB_REPOSITORY
          value: natcws
        - name: GITHUB_PERSONAL_TOKEN 
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_PERSONAL_TOKEN
